#!/bin/sh


usage() {
	cat <<'EOM'
dwl-keys

script to generate key strokes

usage:

Add key bindings for the following commands:

	bind `dwl-keys copy`       to Super+C
	bind `dwl-keys paste`      to Super+V
	bind `dwl-keys cut`        to Super+X
	bind `dwl-keys deleteword` to Super+Backspace

Status bar tag clicks can be bound to these commands:

	`dwl-keys view <tagname>`
	`dwl-keys tag <tagname>`

EOM
	exit 1
}

copy() {
	appid="$1"
	ctype="$2"

	case "$appid" in
		# special cases for certain apps

		foot | footclient )
			wtype -k XF86Copy
			;;

		gnumeric )
			wtype -M ctrl -k Insert
			;;

		# otherwise default behavior dependng on whether we have an
		# Xwayland or wayland client
		*)
			if [ "$ctype" = "2" ]; then
				xdotool getactivewindow key --clearmodifiers ctrl+c
			else
				wtype -M ctrl c
			fi
			;;
	esac
}

paste() {
	appid="$1"
	ctype="$2"

	case "$appid" in

		foot | footclient )
			wtype -k XF86Paste
			;;

		gnumeric )
			wtype -M shift -k Insert
			;;

		*)
			if [ "$ctype" = "2" ]; then
				xdotool getactivewindow key --clearmodifiers ctrl+v
			else
				wtype -M ctrl v
			fi
			;;
	esac
}

cut() {
	appid="$1"
	ctype="$2"

	case "$appid" in

		gnumeric )
			wtype -M shift -k Delete
			;;

		*)
			if [ "$ctype" = "2" ]; then
				xdotool getactivewindow key --clearmodifiers ctrl+x
			else
				wtype -M ctrl x
			fi
			;;
	esac
}

deleteword() {
	appid="$1"
	ctype="$2"

	case "$appid" in

		foot | footclient )
			wtype -M ctrl w
			;;

		*)
			if [ "$ctype" = "2" ]; then
				xdotool getactivewindow key --clearmodifiers ctrl+BackSpace
			else
				wtype -M ctrl -k backspace
			fi
			;;
	esac
}

view() {
	tag="$1"

	echo "$tag" | grep -q '^[a-z]$' || exit

	wtype -M logo r -m logo "$tag"
}

tag() {
	tag="$1"

	echo "$tag" | grep -q '^[a-z]$' || exit

	wtype -M logo -M shift R -m shift -m logo "$tag"
}

command="$1"
case "$command" in
	copy | paste | cut | deleteword )
		read -r appid < $XDG_RUNTIME_DIR/dwl/appid
		read -r ctype < $XDG_RUNTIME_DIR/dwl/ctype
		$command "$appid" "$ctype"
		;;

	tag | view )
		$command "$2"
		;;

	*)
		usage
		;;
esac
