#!/bin/sh

DELAY=1

# scan codes for ydotool
# from here: /usr/include/linux/input-event-codes.h

SHFT=42
CTRL=29
ALT=100
GUI=125 # windows/super key

K_C=46
K_R=19
K_V=47
K_W=17
K_X=45

K_BACKSPACE=14
K_COPY=133
K_PASTE=135

# or define lots of keys
# eval $(awk '$2 ~ /^KEY_/ && $3 ~ /^[0-9]*$/ { print $2 "=" $3 }' /usr/include/linux/input-event-codes.h )
# or even
# eval $(awk '$2 ~ /^KEY_/ && $3 ~ /^(0x)?[0-9]+$/ { print $2 "=" $3 }' /usr/include/linux/input-event-codes.h )

usage() {
	cat <<'EOM'
dwl-keys

script to generate key strokes

usage:

Add key bindings for the following commands:

	bind `dwl-keys copy`       to Super+C
	bind `dwl-keys paste`      to Super+V
	bind `dwl-keys cut`        to Super+X
	bind `dwl-keys deleteword` to Super+Backspace

Status bar tag clicks can be bound to these commands:

	`dwl-keys view <tagname>`
	`dwl-keys tag <tagname>`

EOM
	exit 1
}

copy() {
	appid="$1"

	case "$appid" in
		# special cases for certain apps

		foot | footclient )
			ydotool key --key-delay $DELAY $K_COPY:1 $K_COPY:0
			;;

		gnome-terminal-server | Alacritty )
			ydotool key --key-delay $DELAY $CTRL:1 $SHFT:1 $K_C:1 $K_C:0 $SHFT:0 $CTRL:0
			;;

		URxvt )
			ydotool key --key-delay $DELAY $CTRL:1 $ALT:1 $K_C:1 $K_C:0 $ALT:0 $CTRL:0
			;;

		st-256color )
			ydotool key --key-delay $DELAY $ALT:1 $K_C:1 $K_C:0 $ALT:0
			;;

		*)
			ydotool key --key-delay $DELAY $CTRL:1 $K_C:1 $K_C:0 $CTRL:0
			;;
	esac
}

paste() {
	appid="$1"

	case "$appid" in

		foot | footclient )
			ydotool key --key-delay $DELAY $K_PASTE:1 $K_PASTE:0
			;;

		gnome-terminal-server | Alacritty )
			ydotool key --key-delay $DELAY $CTRL:1 $SHFT:1 $K_V:1 $K_V:0 $SHFT:0 $CTRL:0
			;;

		URxvt )
			ydotool key --key-delay $DELAY $CTRL:1 $ALT:1 $K_V:1 $K_V:0 $ALT:0 $CTRL:0
			;;

		st-256color )
			ydotool key --key-delay $DELAY $ALT:1 $K_V:1 $K_V:0 $ALT:0
			;;

		*)
			ydotool key --key-delay $DELAY $CTRL:1 $K_V:1 $K_V:0 $CTRL:0
			;;
	esac
}

cut() {
	ydotool key --key-delay $DELAY $CTRL:1 $K_X:1 $K_X:0 $CTRL:0
}

deleteword() {
	appid="$1"

	case "$appid" in

		foot | footclient )
			ydotool key --key-delay $DELAY $CTRL:1 $K_W:1 $K_W:0 $CTRL:0
			;;

		*)
			ydotool key --key-delay $DELAY $CTRL:1 $K_BACKSPACE:1 $K_BACKSPACE:0 $CTRL:0
			;;
	esac
}

view() {
	tag="$1"

	echo "$tag" | grep -q '^[a-z]$' || exit

	ydotool key --key-delay $DELAY $GUI:1 $K_R:1 $K_R:0 $GUI:0
	ydotool type $tag
}

tag() {
	tag="$1"

	echo "$tag" | grep -q '^[a-z]$' || exit

	ydotool key --key-delay $DELAY $GUI:1 $SHFT:1 $K_R:1 $K_R:0 $SHFT:0 $GUI:0
	ydotool type $tag
}

command="$1"
case "$command" in
	copy | paste | deleteword )
		read -r appid < "$XDG_RUNTIME_DIR/dwl/appid"
		$command "$appid"
		;;

	cut )
		$command
		;;

	tag | view )
		$command "$2"
		;;

	*)
		usage
		;;
esac
